apiVersion: testbench.agentic-layer.ai/v1alpha1
kind: Experiment
metadata:
  labels:
    app.kubernetes.io/name: testbench-operator
    app.kubernetes.io/managed-by: kustomize
  name: experiment-sample
spec:
  # TODO(user): Add fields here
