apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflowTemplate
metadata:
  name: ragas-run-template
  namespace: testkube
  labels:
    testkube.io/test-category: ragas-evaluation
    app: testworkflows
spec:
  # Configuration parameters for the Agent URL & the Docker Image
  config:
    agentUrl:
      type: string
      description: "URL to the agent endpoint (A2A protocol)"
    image:
      type: string
      description: "Docker image to use for the run step"
      default: "ghcr.io/agentic-layer/testbench/testworkflows:latest"

  # Working directory for the container
  container:
    workingDir: /app
    image: "{{ config.image }}"
    imagePullPolicy: Never

  # Runs the run script with the configured parameters
  steps:
    - name: run-agent-queries
      run:
        args:
          - run.py
          - "{{ config.agentUrl }}"
      artifacts:
        paths:
          - data/experiments/ragas_experiment.jsonl
