apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflowTemplate
metadata:
  name: ragas-setup-template
  namespace: testkube
  labels:
    testkube.io/test-category: ragas-evaluation
    app: testworkflows
spec:
  # Configuration parameters for the Dataset & the Docker Image
  config:
    datasetUrl:
      type: string
      description: "URL to the dataset file (.csv, .json, or .parquet)"
    image:
      type: string
      description: "Docker image to use for the setup step"
      default: "ghcr.io/agentic-layer/testbench/testworkflows:latest"

  # Working directory for the container
  container:
    workingDir: /app
    image: "{{ config.image }}"
    imagePullPolicy: Never

  # Runs the setup script with the configured parameters
  steps:
    - name: setup-dataset
      run:
        args:
          - setup.py
          - "{{ config.datasetUrl }}"
      artifacts:
        paths:
          - data/datasets/ragas_dataset.jsonl
