{
 "title": "Workflow Evaluations",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "workflow", "label": "Workflow Name", "query": { "query": "label_values(workflow_name)" } },
   {
    "name": "metric",
    "query": {
     "query": "label_values(testbench_evaluation_metric,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Token Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(type) (avg by(execution_number, type) (testbench_evaluation_token_usage{workflow_name=\"$workflow\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost Per Test (USD)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(execution_number) (testbench_evaluation_cost{workflow_name=\"$workflow\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens per Test",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(execution_number, type) (testbench_evaluation_token_usage{workflow_name=\"$workflow\", type=\"input_tokens\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(execution_number, type) (testbench_evaluation_token_usage{workflow_name=\"$workflow\", type=\"output_tokens\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Evaluation of $metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "metric" },
  {
   "title": "Average $metric over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg by(name) (last_over_time(testbench_evaluation_metric{name=\"$metric\", workflow_name=\"$workflow\"}[$__interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average $metric per test",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "avg by(execution_number) (testbench_evaluation_metric{workflow_name=\"$workflow\", name=~\"$metric\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Individual $metric results over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "max by(sample_hash, user_input_truncated) (last_over_time(testbench_evaluation_metric{name=\"$metric\", workflow_name=\"$workflow\"}[$__interval]))",
     "legendFormat": "Question: \"{{user_input_truncated}}\""
    }
   ]
  },
  {
   "title": "Individual $metric results per test",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "avg by(sample_hash, trace_id, user_input_truncated, execution_number) (testbench_evaluation_metric{workflow_name=\"$workflow\", name=~\"$metric\"})",
     "legendFormat": "Question: \"{{user_input_truncated}}\""
    }
   ]
  }
 ]
}