{
 "title": "Testkube",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SUCCESSFUL test executions",
   "type": "timeseries",
   "description": "Executions distributions",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "testkube_test_executions_count{result=\"passed\"}",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  },
  {
   "title": "FAILED test executions",
   "type": "timeseries",
   "description": "Executions distributions",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "testkube_test_executions_count{result=\"failed\"}",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  },
  {
   "title": "Test creations",
   "type": "stat",
   "description": "Executions distributions",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "testkube_test_creations_count{}",
     "legendFormat": "{{type}} created"
    },
    {}
   ]
  }
 ]
}